-- ============================================================================
-- HÀNH TRÌNH SỐ - hanhtrinhso.docbuoc.vn
-- Supabase Database Initialization Schema & Authentication System (Idempotent)
-- Sáng lập viên: Huỳnh Ngân Giang | SĐT: 0355782168 | Email: lyngangiang83pt@gmail.com
-- ============================================================================

-- 1. BẢNG TÀI KHOẢN NGƯỜI DÙNG ĐĂNG KÝ / ĐĂNG NHẬP (APP_USERS)
CREATE TABLE IF NOT EXISTS public.app_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    role TEXT DEFAULT 'student' CHECK (role IN ('student', 'teacher', 'admin')),
    is_vip BOOLEAN DEFAULT false,
    avatar_url TEXT DEFAULT 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. BẢNG BẢNG TIN & VĂN BẢN (NEWS)
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('truong', 'vanban', 'thongbao', 'huongnghiep')),
    tag TEXT NOT NULL,
    content TEXT NOT NULL,
    date TEXT NOT NULL,
    author TEXT DEFAULT 'Huỳnh Ngân Giang',
    views INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. BẢNG BÀI GIẢNG (LECTURES: KHỐI 6, 7, 8, 9 - NLS & AI)
CREATE TABLE IF NOT EXISTS public.lectures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade TEXT NOT NULL CHECK (grade IN ('6', '7', '8', '9')),
    title TEXT NOT NULL,
    format TEXT NOT NULL CHECK (format IN ('pptx', 'docx', 'elearning')),
    has_ai BOOLEAN DEFAULT true,
    description TEXT,
    file_url TEXT,
    downloads INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. BẢNG BÀI TẬP & PHIẾU HỌC TẬP (ASSIGNMENTS)
CREATE TABLE IF NOT EXISTS public.assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade TEXT NOT NULL CHECK (grade IN ('6', '7', '8', '9')),
    title TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Phiếu học tập', 'Bài tập về nhà', 'Bài tập dự án')),
    deadline TEXT NOT NULL,
    description TEXT,
    file_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. BẢNG NỘP SẢN PHẨM HỌC SINH (STUDENT SUBMISSIONS)
CREATE TABLE IF NOT EXISTS public.student_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.app_users(id) ON DELETE SET NULL,
    student_name TEXT NOT NULL,
    grade TEXT NOT NULL,
    class_name TEXT,
    project_title TEXT NOT NULL,
    submission_channel TEXT NOT NULL CHECK (submission_channel IN ('padlet', 'drive', 'zalo', 'direct_upload')),
    submission_link TEXT,
    status TEXT DEFAULT 'Đã tiếp nhận' CHECK (status IN ('Đã tiếp nhận', 'Đang chấm', 'Xuất sắc', 'Đạt giải Nhất', 'Đánh giá Cao')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. BẢNG MÃ XÁC THỰC KHO VIP (VIP CODES)
CREATE TABLE IF NOT EXISTS public.vip_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    max_uses INT DEFAULT 1000,
    current_uses INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. BẢNG THÔNG BÁO HỆ THỐNG (ANNOUNCEMENTS)
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    date TEXT NOT NULL,
    is_pinned BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. BẢNG LỊCH SỬ HỎI ĐÁP CHATBOT AI (CHAT LOGS)
CREATE TABLE IF NOT EXISTS public.chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT,
    user_query TEXT NOT NULL,
    ai_response TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================================
-- CẤU HÌNH ROW LEVEL SECURITY (RLS) - TỰ ĐỘNG XÓA POLICY CŨ NẾU ĐÃ TỒN TẠI
-- ============================================================================
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lectures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;

-- Xóa các policy cũ trước khi tạo lại để tránh lỗi 42710
DROP POLICY IF EXISTS "Public Read Users" ON public.app_users;
DROP POLICY IF EXISTS "Public Insert Users" ON public.app_users;
DROP POLICY IF EXISTS "Public Update Users" ON public.app_users;

DROP POLICY IF EXISTS "Public Read News" ON public.news;
DROP POLICY IF EXISTS "Public Read Lectures" ON public.lectures;
DROP POLICY IF EXISTS "Public Read Assignments" ON public.assignments;
DROP POLICY IF EXISTS "Public Read Submissions" ON public.student_submissions;
DROP POLICY IF EXISTS "Public Read Announcements" ON public.announcements;
DROP POLICY IF EXISTS "Public Verify VIP" ON public.vip_codes;

DROP POLICY IF EXISTS "Public Insert Submissions" ON public.student_submissions;
DROP POLICY IF EXISTS "Public Insert Chat Logs" ON public.chat_logs;

-- Tạo các policy mới an toàn
CREATE POLICY "Public Read Users" ON public.app_users FOR SELECT USING (true);
CREATE POLICY "Public Insert Users" ON public.app_users FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Users" ON public.app_users FOR UPDATE USING (true);

CREATE POLICY "Public Read News" ON public.news FOR SELECT USING (true);
CREATE POLICY "Public Read Lectures" ON public.lectures FOR SELECT USING (true);
CREATE POLICY "Public Read Assignments" ON public.assignments FOR SELECT USING (true);
CREATE POLICY "Public Read Submissions" ON public.student_submissions FOR SELECT USING (true);
CREATE POLICY "Public Read Announcements" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "Public Verify VIP" ON public.vip_codes FOR SELECT USING (true);

CREATE POLICY "Public Insert Submissions" ON public.student_submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Insert Chat Logs" ON public.chat_logs FOR INSERT WITH CHECK (true);

-- ============================================================================
-- DỮ LIỆU MẪU BAN ĐẦU (TỰ ĐỘNG BỎ QUA NẾU ĐÃ CÓ)
-- ============================================================================

-- Tài khoản mẫu (Mật khẩu: "123456")
INSERT INTO public.app_users (username, password_hash, full_name, email, phone, role, is_vip) VALUES
('admin_giang', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Huỳnh Ngân Giang', 'lyngangiang83pt@gmail.com', '0355782168', 'admin', true),
('giaovien_mai', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Cô Nguyễn Thị Mai', 'mai.nguyen@edu.vn', '0912345678', 'teacher', true),
('hocsinh_an', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Nguyễn Văn An', 'an.nguyen@gmail.com', '0388999888', 'student', false)
ON CONFLICT (username) DO UPDATE SET full_name = EXCLUDED.full_name, role = EXCLUDED.role, is_vip = EXCLUDED.is_vip;

-- Dữ liệu Mã VIP
INSERT INTO public.vip_codes (code, description, is_active) VALUES
('VIP2026', 'Mã VIP mở khóa Giáo án AI Chuyên Sâu 2026', true),
('DOCBUOC83', 'Mã Đặc quyền Sáng lập viên Huỳnh Ngân Giang', true),
('HANHTRINHSO', 'Mã trải nghiệm Năng lực số cao cấp', true)
ON CONFLICT (code) DO NOTHING;

-- Dữ liệu Bảng tin (chỉ chèn nếu chưa có)
INSERT INTO public.news (category, tag, title, date, content, author)
SELECT 'truong', 'Tin trường', 'Hội thi Thiết kế Học liệu số Tích hợp AI năm học 2025-2026', '05/08/2026', 'Trường phát động hội thi sản phẩm bài giảng số tích hợp Năng lực số (NLS) dành cho học sinh Khối 6-9.', 'Huỳnh Ngân Giang'
WHERE NOT EXISTS (SELECT 1 FROM public.news WHERE title = 'Hội thi Thiết kế Học liệu số Tích hợp AI năm học 2025-2026');

INSERT INTO public.news (category, tag, title, date, content, author)
SELECT 'vanban', 'Văn bản', 'Văn bản Hướng dẫn Thực hiện Khung Năng lực số Phổ thông Mới', '01/08/2026', 'Bộ Giáo dục và Đào tạo ban hành quy định tích hợp kỹ năng công nghệ số vào giáo án giảng dạy.', 'Huỳnh Ngân Giang'
WHERE NOT EXISTS (SELECT 1 FROM public.news WHERE title = 'Văn bản Hướng dẫn Thực hiện Khung Năng lực số Phổ thông Mới');

INSERT INTO public.news (category, tag, title, date, content, author)
SELECT 'thongbao', 'Thông báo', 'Thông báo Lịch nộp Sản phẩm Dự án Kỹ năng số Khối 8 & 9', '30/07/2026', 'Học sinh hoàn thiện video và bài thuyết trình PPTX nộp trước ngày 15/08 trên cổng Padlet hoặc Zalo OA.', 'Huỳnh Ngân Giang'
WHERE NOT EXISTS (SELECT 1 FROM public.news WHERE title = 'Thông báo Lịch nộp Sản phẩm Dự án Kỹ năng số Khối 8 & 9');

INSERT INTO public.news (category, tag, title, date, content, author)
SELECT 'huongnghiep', 'Hướng nghiệp', 'Định hướng Nghề nghiệp Kỷ nguyên AI cho Học sinh THCS', '25/07/2026', 'Chuyên đề giới thiệu các ngành nghề công nghệ mới: Kỹ sư AI, Chuyên gia An toàn thông tin, Nhà phân tích dữ liệu.', 'Huỳnh Ngân Giang'
WHERE NOT EXISTS (SELECT 1 FROM public.news WHERE title = 'Định hướng Nghề nghiệp Kỷ nguyên AI cho Học sinh THCS');

-- Dữ liệu Bài giảng Khối 6-9 (chỉ chèn nếu chưa có)
INSERT INTO public.lectures (grade, title, format, has_ai, description, downloads)
SELECT '6', 'Bài 1: Năng lực số và Công cụ Tìm kiếm An toàn', 'pptx', true, 'Bài giảng Slide PPTX sinh động tích hợp ứng dụng AI tra cứu tri thức dành cho học sinh Khối 6.', 1420
WHERE NOT EXISTS (SELECT 1 FROM public.lectures WHERE title = 'Bài 1: Năng lực số và Công cụ Tìm kiếm An toàn');

INSERT INTO public.lectures (grade, title, format, has_ai, description, downloads)
SELECT '6', 'Phiếu Giáo án: Đạo đức Số & Bảo vệ Thông tin Cá nhân', 'docx', true, 'Kế hoạch bài dạy DOCX chuẩn 5512 tích hợp ma trận Năng lực số (NLS).', 980
WHERE NOT EXISTS (SELECT 1 FROM public.lectures WHERE title = 'Phiếu Giáo án: Đạo đức Số & Bảo vệ Thông tin Cá nhân');

INSERT INTO public.lectures (grade, title, format, has_ai, description, downloads)
SELECT '7', 'Bài 3: Xử lý Dữ liệu Bảng tính với Trợ lý AI', 'pptx', true, 'Hướng dẫn sử dụng hàm Excel/Google Sheets nâng cao kết hợp AI phân tích số liệu.', 1650
WHERE NOT EXISTS (SELECT 1 FROM public.lectures WHERE title = 'Bài 3: Xử lý Dữ liệu Bảng tính với Trợ lý AI');

INSERT INTO public.lectures (grade, title, format, has_ai, description, downloads)
SELECT '7', 'E-learning: Hành trang Kỹ năng Số Tuổi Teen', 'elearning', true, 'Bài giảng Elearning HTML5 tương tác trực tiếp với câu hỏi trắc nghiệm tự động.', 2100
WHERE NOT EXISTS (SELECT 1 FROM public.lectures WHERE title = 'E-learning: Hành trang Kỹ năng Số Tuổi Teen');

INSERT INTO public.lectures (grade, title, format, has_ai, description, downloads)
SELECT '8', 'Bài 5: Lập trình Tư duy Thuật toán & Câu lệnh Prompt AI', 'pptx', true, 'Giáo án PPTX giới thiệu tư duy máy tính và cách giao tiếp với các mô hình AI lớn.', 1890
WHERE NOT EXISTS (SELECT 1 FROM public.lectures WHERE title = 'Bài 5: Lập trình Tư duy Thuật toán & Câu lệnh Prompt AI');

INSERT INTO public.lectures (grade, title, format, has_ai, description, downloads)
SELECT '8', 'Giáo án DOCX: Thiết kế Slide Bài thuyết trình với Canva AI', 'docx', true, 'Tài liệu chi tiết hướng dẫn học sinh tạo bài trình chiếu chuyên nghiệp.', 1340
WHERE NOT EXISTS (SELECT 1 FROM public.lectures WHERE title = 'Giáo án DOCX: Thiết kế Slide Bài thuyết trình với Canva AI');

INSERT INTO public.lectures (grade, title, format, has_ai, description, downloads)
SELECT '9', 'Bài 8: Ôn tập Tổng hợp Năng lực số & Đề án Chuyển đổi số', 'pptx', true, 'Bài giảng chuẩn bị cho kỳ kiểm tra đánh giá Năng lực số lớp 9.', 2450
WHERE NOT EXISTS (SELECT 1 FROM public.lectures WHERE title = 'Bài 8: Ôn tập Tổng hợp Năng lực số & Đề án Chuyển đổi số');

INSERT INTO public.lectures (grade, title, format, has_ai, description, downloads)
SELECT '9', 'E-learning: Thực hành An toàn Thông tin & Quyền Riêng tư', 'elearning', true, 'Mô phỏng các tình huống an toàn mạng thực tế dành cho học sinh cuối cấp.', 1780
WHERE NOT EXISTS (SELECT 1 FROM public.lectures WHERE title = 'E-learning: Thực hành An toàn Thông tin & Quyền Riêng tư');

-- Dữ liệu Bài tập
INSERT INTO public.assignments (grade, title, type, deadline, description)
SELECT '6', 'Phiếu học tập #1: Phân biệt Tin giả & Tin thật trên Mạng', 'Phiếu học tập', '15/08/2026', 'Rèn luyện kỹ năng nhận diện nguồn tin cậy trên internet.'
WHERE NOT EXISTS (SELECT 1 FROM public.assignments WHERE title = 'Phiếu học tập #1: Phân biệt Tin giả & Tin thật trên Mạng');

INSERT INTO public.assignments (grade, title, type, deadline, description)
SELECT '7', 'Bài tập về nhà #2: Thực hành Viết Prompt AI tạo Dàn ý Bài văn', 'Bài tập về nhà', '18/08/2026', 'Tập tương tác và tinh chỉnh câu lệnh với Trợ lý AI.'
WHERE NOT EXISTS (SELECT 1 FROM public.assignments WHERE title = 'Bài tập về nhà #2: Thực hành Viết Prompt AI tạo Dàn ý Bài văn');

INSERT INTO public.assignments (grade, title, type, deadline, description)
SELECT '8', 'Phiếu bài tập #3: Phân tích Dữ liệu Số & Vẽ Biểu đồ', 'Phiếu học tập', '20/08/2026', 'Thực hành tính toán và trực quan hóa số liệu.'
WHERE NOT EXISTS (SELECT 1 FROM public.assignments WHERE title = 'Phiếu bài tập #3: Phân tích Dữ liệu Số & Vẽ Biểu đồ');

INSERT INTO public.assignments (grade, title, type, deadline, description)
SELECT '9', 'Dự án Cuối khóa: Thiết kế Infographic Hướng nghiệp Số', 'Bài tập dự án', '25/08/2026', 'Thiết kế sản phẩm truyền thông định hướng ngành nghề số.'
WHERE NOT EXISTS (SELECT 1 FROM public.assignments WHERE title = 'Dự án Cuối khóa: Thiết kế Infographic Hướng nghiệp Số');

-- Dữ liệu Thông báo
INSERT INTO public.announcements (title, description, date, is_pinned)
SELECT '🔥 Cập nhật hệ thống: Tích hợp Trợ lý AI Hỏi - Đáp 24/7 Mới', 'Hệ thống đã cập nhật AI trả lời trực tiếp 24/24 cho học sinh Khối 6-9.', '06/08/2026', true
WHERE NOT EXISTS (SELECT 1 FROM public.announcements WHERE title = '🔥 Cập nhật hệ thống: Tích hợp Trợ lý AI Hỏi - Đáp 24/7 Mới');

INSERT INTO public.announcements (title, description, date, is_pinned)
SELECT '📢 Đã tải lên Bộ Bài Giảng PPTX NLS Khối 8 & Khối 9 Mới', 'Các cô giáo và học sinh có thể vào phân hệ Bài Giảng để tải về bài học mới nhất.', '03/08/2026', false
WHERE NOT EXISTS (SELECT 1 FROM public.announcements WHERE title = '📢 Đã tải lên Bộ Bài Giảng PPTX NLS Khối 8 & Khối 9 Mới');

INSERT INTO public.announcements (title, description, date, is_pinned)
SELECT '🌟 Mở khóa Kho VIP với Mã VIP2026 cho Thành viên Thử nghiệm', 'Nhập mã VIP2026 để trải nghiệm bộ giáo án và trợ lý AI nâng cao.', '01/08/2026', false
WHERE NOT EXISTS (SELECT 1 FROM public.announcements WHERE title = '🌟 Mở khóa Kho VIP với Mã VIP2026 cho Thành viên Thử nghiệm');
